export const STATES_AND_DISTRICTS = [
  {
    state: 'Maharashtra',
    stateCode: 'MH',
    hindi: 'महाराष्ट्र',
    marathi: 'महाराष्ट्र',
    agroZone: 'Western Plateau & Hills (Deccan)',
    majorCrops: ['Onion', 'Soybean', 'Cotton', 'Tomato', 'Grapes', 'Sugarcane', 'Pomegranate'],
    totalApms: 305,
    enamLinkedPercent: 88,
    districts: [
      { name: 'Nashik', defaultPincode: '422001', hub: 'Lasalgaon / Pimpalgaon', lat: 20.0059, lng: 75.3200, topCrop: 'Onion & Tomato', soilType: 'Black & Red Loamy', mandisCount: 14 },
      { name: 'Pune', defaultPincode: '411001', hub: 'Gultekdi / Manchar / Junnar', lat: 18.5204, lng: 73.8567, topCrop: 'Tomato, Potato & Vegetables', soilType: 'Medium Black Clay', mandisCount: 18 },
      { name: 'Ahmednagar', defaultPincode: '414001', hub: 'Rahata / Shrirampur / Kopargaon', lat: 19.0948, lng: 74.7480, topCrop: 'Onion, Soybean & Pomegranate', soilType: 'Deep Black Soil', mandisCount: 12 },
      { name: 'Solapur', defaultPincode: '413001', hub: 'Solapur City / Barshi / Pandharpur', lat: 17.6599, lng: 75.9064, topCrop: 'Pomegranate, Onion & Jowar', soilType: 'Black Cotton Soil', mandisCount: 11 },
      { name: 'Latur', defaultPincode: '413512', hub: 'Latur APMC Pulse & Oilseed Node', lat: 18.4088, lng: 76.5604, topCrop: 'Soybean & Pulses (Tur/Chana)', soilType: 'Heavy Clay Soil', mandisCount: 8 },
      { name: 'Jalgaon', defaultPincode: '425001', hub: 'Jalgaon Banana & Cotton Mandi', lat: 21.0077, lng: 75.5626, topCrop: 'Banana & Cotton', soilType: 'Rich Alluvial Black', mandisCount: 13 },
      { name: 'Nagpur', defaultPincode: '440001', hub: 'Kalamna Mandi Nagpur', lat: 21.1458, lng: 79.0882, topCrop: 'Orange, Soybean & Cotton', soilType: 'Black Clay Loam', mandisCount: 9 },
      { name: 'Kolhapur', defaultPincode: '416001', hub: 'Kolhapur Shahu Market Yard', lat: 16.7050, lng: 74.2433, topCrop: 'Jaggery, Sugarcane & Vegetables', soilType: 'Laterite & Red Loam', mandisCount: 7 },
      { name: 'Chhatrapati Sambhajinagar', defaultPincode: '431001', hub: 'Jadhavwadi Market Yard', lat: 19.8762, lng: 75.3433, topCrop: 'Cotton, Maize & Sweet Lime', soilType: 'Medium Black', mandisCount: 10 },
      { name: 'Amravati', defaultPincode: '444601', hub: 'Amravati Cotton & Grain APMC', lat: 20.9374, lng: 77.7796, topCrop: 'Cotton & Soybean', soilType: 'Deep Black Cotton', mandisCount: 8 }
    ]
  },
  {
    state: 'Madhya Pradesh',
    stateCode: 'MP',
    hindi: 'मध्य प्रदेश',
    marathi: 'मध्य प्रदेश',
    agroZone: 'Central Plateau & Malwa Region',
    majorCrops: ['Soybean', 'Wheat', 'Garlic', 'Chana', 'Mustard', 'Coriander'],
    totalApms: 259,
    enamLinkedPercent: 92,
    districts: [
      { name: 'Indore', defaultPincode: '452001', hub: 'Choithram Mandi / Laxmibai Nagar', lat: 22.7196, lng: 75.8577, topCrop: 'Soybean, Wheat & Potato', soilType: 'Medium Black Clay', mandisCount: 11 },
      { name: 'Ujjain', defaultPincode: '456001', hub: 'Chimanganj Mandi Ujjain', lat: 23.1765, lng: 75.7885, topCrop: 'Wheat (Sharbati) & Soybean', soilType: 'Malwa Black Soil', mandisCount: 9 },
      { name: 'Mandsaur', defaultPincode: '458001', hub: 'Mandsaur Garlic & Spices Mandi', lat: 24.0722, lng: 75.0674, topCrop: 'Garlic, Spices & Opium Seed', soilType: 'Black Loamy', mandisCount: 8 },
      { name: 'Neemuch', defaultPincode: '458441', hub: 'Neemuch Grain, Seed & Herb Hub', lat: 24.4727, lng: 74.8700, topCrop: 'Garlic, Wheat & Ashwagandha', soilType: 'Clayey Loam', mandisCount: 6 },
      { name: 'Dewas', defaultPincode: '455001', hub: 'Dewas Main APMC Yard', lat: 22.9676, lng: 76.0534, topCrop: 'Soybean & Gram', soilType: 'Deep Black Soil', mandisCount: 7 },
      { name: 'Bhopal', defaultPincode: '462001', hub: 'Karond Mandi Bhopal', lat: 23.2599, lng: 77.4126, topCrop: 'Wheat & Pulses', soilType: 'Mixed Red & Black', mandisCount: 5 },
      { name: 'Ratlam', defaultPincode: '457001', hub: 'Ratlam Namkeen & Grain APMC', lat: 23.3315, lng: 75.0367, topCrop: 'Garlic, Onion & Soybean', soilType: 'Black Soil', mandisCount: 6 },
      { name: 'Khargone', defaultPincode: '451001', hub: 'Sanawad & Khargone Cotton Hub', lat: 21.8234, lng: 75.6086, topCrop: 'Cotton & Chilli', soilType: 'Black Cotton', mandisCount: 7 }
    ]
  },
  {
    state: 'Karnataka',
    stateCode: 'KA',
    hindi: 'कर्नाटक',
    marathi: 'कर्नाटक',
    agroZone: 'Southern Plateau & Coastal Agro Climatic Zone',
    majorCrops: ['Tomato', 'Byadgi Chilli', 'Ragi', 'Maize', 'Paddy', 'Turmeric'],
    totalApms: 162,
    enamLinkedPercent: 85,
    districts: [
      { name: 'Kolar', defaultPincode: '563101', hub: 'Kolar APMC Tomato Special Market', lat: 13.1367, lng: 78.1291, topCrop: 'Tomato & Vegetables', soilType: 'Red Sandy Loam', mandisCount: 6 },
      { name: 'Bengaluru Rural', defaultPincode: '562110', hub: 'Yeshwanthpur & Doddaballapur APMC', lat: 13.0238, lng: 77.5529, topCrop: 'Vegetables & Floriculture', soilType: 'Red Loam', mandisCount: 8 },
      { name: 'Belagavi', defaultPincode: '590001', hub: 'Belagavi Main & Bailhongal APMC', lat: 15.8497, lng: 74.4977, topCrop: 'Sugarcane, Vegetables & Maize', soilType: 'Mixed Black & Red', mandisCount: 10 },
      { name: 'Haveri', defaultPincode: '581110', hub: 'Byadgi Red Chilli Marketing Yard', lat: 14.6823, lng: 75.4855, topCrop: 'Byadagi Chilli & Cotton', soilType: 'Medium Black Soil', mandisCount: 7 },
      { name: 'Mysuru', defaultPincode: '570001', hub: 'Bandipalya APMC Yard Mysore', lat: 12.2958, lng: 76.6394, topCrop: 'Paddy, Ragi & Turmeric', soilType: 'Red Sandy', mandisCount: 6 },
      { name: 'Davanagere', defaultPincode: '577001', hub: 'Davanagere Maize & Areca Market', lat: 14.4644, lng: 75.9218, topCrop: 'Maize & Cotton', soilType: 'Black & Red Soil', mandisCount: 5 }
    ]
  },
  {
    state: 'Punjab',
    stateCode: 'PB',
    hindi: 'पंजाब',
    marathi: 'पंजाब',
    agroZone: 'Trans-Gangetic Plains & Fertile Alluvial',
    majorCrops: ['Wheat', 'Paddy/Basmati', 'Potato', 'Cotton', 'Mustard', 'Maize'],
    totalApms: 152,
    enamLinkedPercent: 94,
    districts: [
      { name: 'Ludhiana', defaultPincode: '141001', hub: 'Ludhiana Main Dana Mandi & Gill Road', lat: 30.9010, lng: 75.8573, topCrop: 'Wheat & Paddy', soilType: 'Alluvial Loam', mandisCount: 14 },
      { name: 'Khanna', defaultPincode: '141401', hub: 'Khanna Asia Largest Grain Mandi', lat: 30.7073, lng: 76.2166, topCrop: 'Wheat (Grade 1) & Paddy', soilType: 'Rich Alluvial', mandisCount: 6 },
      { name: 'Jalandhar', defaultPincode: '144001', hub: 'Maqsudan Mandi Jalandhar', lat: 31.3260, lng: 75.5762, topCrop: 'Potato & Wheat', soilType: 'Sandy Loam', mandisCount: 11 },
      { name: 'Amritsar', defaultPincode: '143001', hub: 'Bhagtanwala Grain Market Amritsar', lat: 31.6340, lng: 74.8723, topCrop: 'Basmati Rice & Wheat', soilType: 'Alluvial Clay', mandisCount: 9 },
      { name: 'Bathinda', defaultPincode: '151001', hub: 'Bathinda Cotton & Grain Market', lat: 30.2110, lng: 74.9455, topCrop: 'Cotton & Wheat', soilType: 'Arid Sandy Loam', mandisCount: 8 }
    ]
  },
  {
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    hindi: 'उत्तर प्रदेश',
    marathi: 'उत्तर प्रदेश',
    agroZone: 'Upper & Middle Gangetic Plain',
    majorCrops: ['Potato', 'Wheat', 'Sugarcane', 'Paddy', 'Mustard', 'Mango'],
    totalApms: 251,
    enamLinkedPercent: 89,
    districts: [
      { name: 'Agra', defaultPincode: '282001', hub: 'Khandari / Fatehabad Potato Mandi', lat: 27.1767, lng: 78.0081, topCrop: 'Potato & Mustard', soilType: 'Alluvial Sandy', mandisCount: 12 },
      { name: 'Farrukhabad', defaultPincode: '209625', hub: 'Saat Rasta National Potato Terminal', lat: 27.3828, lng: 79.5828, topCrop: 'Potato & Garlic', soilType: 'Gangetic Alluvium', mandisCount: 7 },
      { name: 'Kanpur', defaultPincode: '208001', hub: 'Chakeri / Cooperganj Mandi', lat: 26.4499, lng: 80.3319, topCrop: 'Wheat, Pulses & Oilseeds', soilType: 'Alluvial Loam', mandisCount: 9 },
      { name: 'Varanasi', defaultPincode: '221001', hub: 'Chandasi / Paharia Market Yard', lat: 25.3176, lng: 82.9739, topCrop: 'Vegetables & Paddy', soilType: 'Clayey Alluvium', mandisCount: 6 },
      { name: 'Meerut', defaultPincode: '250001', hub: 'Meerut Delhigate & Transport Nagar', lat: 28.9845, lng: 77.7064, topCrop: 'Sugarcane, Wheat & Potato', soilType: 'Fertile Loam', mandisCount: 8 }
    ]
  },
  {
    state: 'Gujarat',
    stateCode: 'GJ',
    hindi: 'गुजरात',
    marathi: 'गुजरात',
    agroZone: 'Gujarat Plains & Saurashtra Hills',
    majorCrops: ['Cotton', 'Groundnut', 'Cumin', 'Castor', 'Onion', 'Sesame'],
    totalApms: 224,
    enamLinkedPercent: 91,
    districts: [
      { name: 'Rajkot', defaultPincode: '360001', hub: 'Bedi Marketing Yard Rajkot', lat: 22.3039, lng: 70.8022, topCrop: 'Groundnut, Cotton & Cumin', soilType: 'Medium Black Clay', mandisCount: 10 },
      { name: 'Gondal', defaultPincode: '360311', hub: 'Gondal APMC Mega Marketing Yard', lat: 21.9619, lng: 70.7938, topCrop: 'Groundnut, Chilli & Onion', soilType: 'Black Cotton Soil', mandisCount: 5 },
      { name: 'Surat', defaultPincode: '395003', hub: 'APMC Sardar Market Surat', lat: 21.1702, lng: 72.8311, topCrop: 'Vegetables, Banana & Paddy', soilType: 'Deep Alluvial Clay', mandisCount: 8 },
      { name: 'Unjha (Mehsana)', defaultPincode: '384170', hub: 'Unjha Asia Largest Spice Yard', lat: 23.8037, lng: 72.3920, topCrop: 'Cumin (Jeera), Fennel & Isabgol', soilType: 'Sandy Loam', mandisCount: 6 }
    ]
  },
  {
    state: 'Rajasthan',
    stateCode: 'RJ',
    hindi: 'राजस्थान',
    marathi: 'राजस्थान',
    agroZone: 'Western Dry & Semi-Arid Zone',
    majorCrops: ['Mustard', 'Garlic', 'Wheat', 'Gram', 'Coriander', 'Guar'],
    totalApms: 145,
    enamLinkedPercent: 87,
    districts: [
      { name: 'Kota', defaultPincode: '324001', hub: 'Bhamashah Mandi Kota', lat: 25.2138, lng: 75.8648, topCrop: 'Garlic, Soybean, Mustard & Coriander', soilType: 'Black Clayey', mandisCount: 7 },
      { name: 'Jaipur', defaultPincode: '302001', hub: 'Muhana Mandi Jaipur Mega Terminal', lat: 26.9124, lng: 75.7873, topCrop: 'Wheat, Mustard & Vegetables', soilType: 'Sandy Loam', mandisCount: 9 },
      { name: 'Sri Ganganagar', defaultPincode: '335001', hub: 'Sri Ganganagar Grain & Cotton APMC', lat: 29.9038, lng: 73.8772, topCrop: 'Wheat, Cotton, Mustard & Kinnow', soilType: 'Canal Alluvium', mandisCount: 8 }
    ]
  },
  {
    state: 'Haryana',
    stateCode: 'HR',
    hindi: 'हरियाणा',
    marathi: 'हरियाणा',
    agroZone: 'North-Western Plains Region',
    majorCrops: ['Wheat', 'Basmati Rice', 'Mustard', 'Cotton', 'Sugarcane'],
    totalApms: 114,
    enamLinkedPercent: 96,
    districts: [
      { name: 'Karnal', defaultPincode: '132001', hub: 'Karnal Grain & Basmati Market', lat: 29.6857, lng: 76.9905, topCrop: 'Basmati Rice & Wheat', soilType: 'Alluvial Loam', mandisCount: 8 },
      { name: 'Sirsa', defaultPincode: '125055', hub: 'Sirsa Grain & Cotton Mandi', lat: 29.5349, lng: 75.0290, topCrop: 'Cotton & Wheat', soilType: 'Light Loam', mandisCount: 7 },
      { name: 'Hisar', defaultPincode: '125001', hub: 'Hisar Dana Mandi', lat: 29.1492, lng: 75.7217, topCrop: 'Mustard, Wheat & Cotton', soilType: 'Sandy Loam', mandisCount: 6 }
    ]
  },
  {
    state: 'Telangana',
    stateCode: 'TS',
    hindi: 'तेलंगाना',
    marathi: 'तेलंगाना',
    agroZone: 'Southern Telangana Plateau',
    majorCrops: ['Red Chilli', 'Cotton', 'Paddy', 'Turmeric', 'Maize'],
    totalApms: 180,
    enamLinkedPercent: 86,
    districts: [
      { name: 'Khammam', defaultPincode: '507001', hub: 'Khammam Chilli & Cotton Yard', lat: 17.2473, lng: 80.1514, topCrop: 'Red Chilli & Cotton', soilType: 'Red Chalkas & Black', mandisCount: 6 },
      { name: 'Warangal', defaultPincode: '506002', hub: 'Enumamula Agriculture Market Yard', lat: 17.9689, lng: 79.5941, topCrop: 'Cotton, Chilli & Turmeric', soilType: 'Black Cotton Soil', mandisCount: 8 },
      { name: 'Nizamabad', defaultPincode: '503001', hub: 'Nizamabad Turmeric & Grain APMC', lat: 18.6725, lng: 78.0941, topCrop: 'Turmeric & Paddy', soilType: 'Red Loam', mandisCount: 5 }
    ]
  },
  {
    state: 'Andhra Pradesh',
    stateCode: 'AP',
    hindi: 'आंध्र प्रदेश',
    marathi: 'आंध्र प्रदेश',
    agroZone: 'Krishna-Godavari & Rayalaseema Plains',
    majorCrops: ['Guntur Chilli', 'Tomato', 'Tobacco', 'Paddy', 'Cotton', 'Mango'],
    totalApms: 191,
    enamLinkedPercent: 88,
    districts: [
      { name: 'Guntur', defaultPincode: '522001', hub: 'Guntur Asia Largest Red Chilli Yard', lat: 16.3067, lng: 80.4365, topCrop: 'Red Chilli & Cotton', soilType: 'Deep Black Soil', mandisCount: 9 },
      { name: 'Chittoor (Madanapalle)', defaultPincode: '517325', hub: 'Madanapalle Tomato Mega Market', lat: 13.5500, lng: 78.5000, topCrop: 'Tomato & Mango', soilType: 'Red Sandy Loam', mandisCount: 7 },
      { name: 'Kurnool', defaultPincode: '518001', hub: 'Kurnool Onion & Groundnut Yard', lat: 15.8281, lng: 78.0373, topCrop: 'Onion, Groundnut & Cotton', soilType: 'Black & Red Mixed', mandisCount: 6 }
    ]
  }
];

export const ALL_MANDIS = [
  // Maharashtra Cluster
  {
    id: 'lasalgaon-apmc',
    name: 'Lasalgaon APMC Market',
    marathiName: 'लासलगाव कृषी उत्पन्न बाजार समिती',
    hindiName: 'लासलगांव एपीएमसी मंडी',
    state: 'Maharashtra',
    district: 'Nashik',
    lat: 20.1472,
    lng: 74.2284,
    marketFeePercent: 1.05,
    weighingFeePerQuintal: 4,
    unloadingFeePerQuintal: 8,
    isEnamLinked: true,
    rating: 4.8,
    facilities: ['e-NAM Electronic Auction', 'Digital Weighbridge', 'Large Covered Sheds', 'Farmer Rest House', 'Testing Lab'],
    dailyArrivalTonnes: 1850,
    crowdLevel: 'Moderate to High',
    primaryCommodities: ['onion', 'wheat', 'soybean', 'tomato', 'potato']
  },
  {
    id: 'pimpalgaon-apmc',
    name: 'Pimpalgaon Baswant APMC',
    marathiName: 'पिंपळगाव बसवंत बाजार समिती',
    hindiName: 'पिंपलगांव बसवंत एपीएमसी',
    state: 'Maharashtra',
    district: 'Nashik',
    lat: 20.1704,
    lng: 73.9856,
    marketFeePercent: 1.0,
    weighingFeePerQuintal: 3.5,
    unloadingFeePerQuintal: 7,
    isEnamLinked: true,
    rating: 4.7,
    facilities: ['Rapid Automated Bidding', 'Cold Storage Access', 'Weighbridges', 'Direct Banking'],
    dailyArrivalTonnes: 2100,
    crowdLevel: 'High',
    primaryCommodities: ['onion', 'tomato', 'grapes', 'garlic', 'chilli']
  },
  {
    id: 'yeola-apmc',
    name: 'Yeola APMC Sub-Yard',
    marathiName: 'येवला कृषी बाजार',
    hindiName: 'येवला एपीएमसी उप-मंडी',
    state: 'Maharashtra',
    district: 'Nashik',
    lat: 20.0433,
    lng: 74.4892,
    marketFeePercent: 1.1,
    weighingFeePerQuintal: 4,
    unloadingFeePerQuintal: 6,
    isEnamLinked: true,
    rating: 4.3,
    facilities: ['Direct Buyer Counter', 'Electronic Scales', 'Quick Settlement'],
    dailyArrivalTonnes: 920,
    crowdLevel: 'Low to Moderate',
    primaryCommodities: ['onion', 'wheat', 'cotton', 'soybean']
  },
  {
    id: 'nashik-city-apmc',
    name: 'Nashik Dindori Road APMC',
    marathiName: 'नाशिक मुख्य बाजार समिती (दिंडोरी रोड)',
    hindiName: 'नासिक मुख्य मंडी (दिंडोरी रोड)',
    state: 'Maharashtra',
    district: 'Nashik',
    lat: 20.0245,
    lng: 73.7915,
    marketFeePercent: 1.2,
    weighingFeePerQuintal: 5,
    unloadingFeePerQuintal: 9,
    isEnamLinked: false,
    rating: 4.4,
    facilities: ['Retail & Wholesale Trade', 'Cold Van Parking', 'Weighbridge'],
    dailyArrivalTonnes: 1400,
    crowdLevel: 'High',
    primaryCommodities: ['onion', 'tomato', 'potato', 'vegetables', 'chilli']
  },
  {
    id: 'pune-gultekdi-apmc',
    name: 'Pune Gultekdi Market Yard',
    marathiName: 'पुणे गुलटेकडी कृषी उत्पन्न बाजार',
    hindiName: 'पुणे गुलटेकड़ी मार्केट यार्ड',
    state: 'Maharashtra',
    district: 'Pune',
    lat: 18.4912,
    lng: 73.8644,
    marketFeePercent: 1.25,
    weighingFeePerQuintal: 5,
    unloadingFeePerQuintal: 10,
    isEnamLinked: true,
    rating: 4.6,
    facilities: ['Metropolitan Buyer Hub', '24x7 Unloading', 'FPO Dedicated Platform', 'Cold Chain'],
    dailyArrivalTonnes: 3200,
    crowdLevel: 'Very High',
    primaryCommodities: ['onion', 'tomato', 'potato', 'garlic', 'chilli', 'wheat']
  },
  {
    id: 'rahata-apmc',
    name: 'Rahata APMC (Shirdi Cluster)',
    marathiName: 'राहाता कृषी उत्पन्न बाजार',
    hindiName: 'राहाता एपीएमसी मंडी',
    state: 'Maharashtra',
    district: 'Ahmednagar',
    lat: 19.6974,
    lng: 74.4842,
    marketFeePercent: 1.0,
    weighingFeePerQuintal: 3.5,
    unloadingFeePerQuintal: 6.5,
    isEnamLinked: true,
    rating: 4.2,
    facilities: ['Weighbridge', 'Farmer Shade', 'Canteen'],
    dailyArrivalTonnes: 750,
    crowdLevel: 'Low',
    primaryCommodities: ['onion', 'soybean', 'wheat', 'potato']
  },
  {
    id: 'latur-grain-apmc',
    name: 'Latur Main Grain & Oilseed APMC',
    marathiName: 'लातूर मुख्य डाळ व तेलबिया बाजार समिती',
    hindiName: 'लातूर मुख्य अनाज व तिलहन मंडी',
    state: 'Maharashtra',
    district: 'Latur',
    lat: 18.4012,
    lng: 76.5750,
    marketFeePercent: 1.05,
    weighingFeePerQuintal: 4,
    unloadingFeePerQuintal: 7,
    isEnamLinked: true,
    rating: 4.8,
    facilities: ['National Pulse/Soy Pricing Node', 'Automated Grading Lab', 'Direct Miller Network'],
    dailyArrivalTonnes: 4500,
    crowdLevel: 'High',
    primaryCommodities: ['soybean', 'wheat', 'pulses', 'cotton']
  },
  {
    id: 'solapur-apmc',
    name: 'Solapur Siddheshwar APMC Yard',
    marathiName: 'सोलापूर सिद्धेश्वर कृषी उत्पन्न बाजार',
    hindiName: 'सोलापूर सिद्धेश्वर एपीएमसी मंडी',
    state: 'Maharashtra',
    district: 'Solapur',
    lat: 17.6680,
    lng: 75.9120,
    marketFeePercent: 1.15,
    weighingFeePerQuintal: 4,
    unloadingFeePerQuintal: 8,
    isEnamLinked: true,
    rating: 4.5,
    facilities: ['Pomegranate & Onion Specialized Sheds', 'Electronic Gate Pass'],
    dailyArrivalTonnes: 1950,
    crowdLevel: 'Moderate',
    primaryCommodities: ['onion', 'pomegranate', 'wheat', 'soybean']
  },
  {
    id: 'jalgaon-apmc',
    name: 'Jalgaon Cotton & Banana Yard',
    marathiName: 'जळगाव मुख्य बाजार समिती',
    hindiName: 'जलगांव मुख्य मंडी यार्ड',
    state: 'Maharashtra',
    district: 'Jalgaon',
    lat: 21.0020,
    lng: 75.5680,
    marketFeePercent: 1.1,
    weighingFeePerQuintal: 3.5,
    unloadingFeePerQuintal: 7,
    isEnamLinked: true,
    rating: 4.4,
    facilities: ['Ginning Mills Direct Weighment', 'Farmer Help Desk'],
    dailyArrivalTonnes: 2300,
    crowdLevel: 'Moderate',
    primaryCommodities: ['cotton', 'soybean', 'wheat', 'banana']
  },

  // Madhya Pradesh Cluster
  {
    id: 'indore-choithram-apmc',
    name: 'Indore Choithram APMC Mandi',
    marathiName: 'इंदूर चोइथराम कृषी मंडी',
    hindiName: 'इंदौर चोइथराम एपीएमसी मंडी',
    state: 'Madhya Pradesh',
    district: 'Indore',
    lat: 22.6840,
    lng: 75.8450,
    marketFeePercent: 1.5,
    weighingFeePerQuintal: 4,
    unloadingFeePerQuintal: 8,
    isEnamLinked: true,
    rating: 4.7,
    facilities: ['Central India Megamarket', 'e-NAM Live Bidding', 'Bulk Storage Silos', 'Banking Counter'],
    dailyArrivalTonnes: 5200,
    crowdLevel: 'High',
    primaryCommodities: ['soybean', 'wheat', 'garlic', 'potato', 'onion']
  },
  {
    id: 'mandsaur-krishi-mandi',
    name: 'Mandsaur Krishi Upaj Mandi',
    marathiName: 'मंदसौर कृषी उत्पन्न मंडी',
    hindiName: 'मंदसौर कृषि उपज मंडी (लहसुन विशेष)',
    state: 'Madhya Pradesh',
    district: 'Mandsaur',
    lat: 24.0680,
    lng: 75.0740,
    marketFeePercent: 1.2,
    weighingFeePerQuintal: 4,
    unloadingFeePerQuintal: 7,
    isEnamLinked: true,
    rating: 4.9,
    facilities: ['India Garlic Benchmark Hub', 'Quality Grading Assayer', 'Electronic Displays'],
    dailyArrivalTonnes: 3100,
    crowdLevel: 'Very High',
    primaryCommodities: ['garlic', 'soybean', 'wheat', 'onion', 'chilli']
  },
  {
    id: 'neemuch-mandi',
    name: 'Neemuch Krishi Upaj Mandi',
    marathiName: 'नीमच कृषी मंडी',
    hindiName: 'नीमच कृषि उपज मंडी',
    state: 'Madhya Pradesh',
    district: 'Neemuch',
    lat: 24.4680,
    lng: 74.8810,
    marketFeePercent: 1.15,
    weighingFeePerQuintal: 3.5,
    unloadingFeePerQuintal: 6.5,
    isEnamLinked: true,
    rating: 4.6,
    facilities: ['Medicinal & Seed Hub', 'Weighbridges', 'Warehouse Receipt Financing'],
    dailyArrivalTonnes: 2600,
    crowdLevel: 'Moderate',
    primaryCommodities: ['garlic', 'wheat', 'soybean', 'cotton']
  },
  {
    id: 'ujjain-chimanganj',
    name: 'Ujjain Chimanganj Krishi Mandi',
    marathiName: 'उज्जैन चिमणगंज मंडी',
    hindiName: 'उज्जैन चिमनगंज कृषि उपज मंडी',
    state: 'Madhya Pradesh',
    district: 'Ujjain',
    lat: 23.1810,
    lng: 75.7920,
    marketFeePercent: 1.3,
    weighingFeePerQuintal: 4,
    unloadingFeePerQuintal: 7.5,
    isEnamLinked: true,
    rating: 4.5,
    facilities: ['e-NAM Yard', 'Farmer Shelter', 'Soil Testing Lab'],
    dailyArrivalTonnes: 3800,
    crowdLevel: 'High',
    primaryCommodities: ['wheat', 'soybean', 'garlic', 'gram']
  },

  // Karnataka Cluster
  {
    id: 'kolar-tomato-market',
    name: 'Kolar APMC Tomato Special Market',
    marathiName: 'कोलार टोमॅटो मार्केट यार्ड',
    hindiName: 'कोलार एपीएमसी विशेष टमाटर मंडी',
    state: 'Karnataka',
    district: 'Kolar',
    lat: 13.1340,
    lng: 78.1380,
    marketFeePercent: 1.2,
    weighingFeePerQuintal: 3,
    unloadingFeePerQuintal: 6,
    isEnamLinked: true,
    rating: 4.8,
    facilities: ['Asia 2nd Largest Tomato Yard', 'Immediate Auctioning', 'Cold Staging Space', 'Crate Washing'],
    dailyArrivalTonnes: 3800,
    crowdLevel: 'Very High',
    primaryCommodities: ['tomato', 'chilli', 'potato', 'vegetables']
  },
  {
    id: 'yeshwanthpur-bengaluru',
    name: 'Bengaluru Yeshwanthpur APMC Yard',
    marathiName: 'बंगळूरू यशवंतपूर कृषी उत्पन्न बाजार',
    hindiName: 'बेंगलुरु यशवंतपुर एपीएमसी मार्केट',
    state: 'Karnataka',
    district: 'Bengaluru Rural',
    lat: 13.0210,
    lng: 77.5480,
    marketFeePercent: 1.5,
    weighingFeePerQuintal: 5,
    unloadingFeePerQuintal: 10,
    isEnamLinked: true,
    rating: 4.5,
    facilities: ['High Consumption Metropolis Hub', 'FPO Priority Gate', 'Multi-commodity Terminal'],
    dailyArrivalTonnes: 4200,
    crowdLevel: 'High',
    primaryCommodities: ['onion', 'tomato', 'potato', 'garlic', 'wheat']
  },
  {
    id: 'byadgi-chilli-yard',
    name: 'Byadgi APMC Red Chilli Yard',
    marathiName: 'ब्याडगी मिरची मार्केट यार्ड',
    hindiName: 'ब्याडगी लाल मिर्च अंतरराष्ट्रीय मंडी',
    state: 'Karnataka',
    district: 'Haveri',
    lat: 14.6850,
    lng: 75.4880,
    marketFeePercent: 1.0,
    weighingFeePerQuintal: 3,
    unloadingFeePerQuintal: 6,
    isEnamLinked: true,
    rating: 4.9,
    facilities: ['International Oleoresin Extraction Hub', 'Color Quality Assayer', 'Direct Exporter Counters'],
    dailyArrivalTonnes: 3400,
    crowdLevel: 'High',
    primaryCommodities: ['chilli', 'cotton', 'garlic']
  },

  // Punjab Cluster
  {
    id: 'khanna-grain-mandi',
    name: 'Khanna Asia Largest Grain Mandi',
    marathiName: 'खन्ना धान्य मंडी (पंजाब)',
    hindiName: 'खन्ना एशिया की सबसे बड़ी अनाज मंडी',
    state: 'Punjab',
    district: 'Khanna',
    lat: 30.7050,
    lng: 76.2210,
    marketFeePercent: 1.0,
    weighingFeePerQuintal: 3,
    unloadingFeePerQuintal: 5,
    isEnamLinked: true,
    rating: 4.9,
    facilities: ['High Speed Grain Cleaners', 'FCI Procurement Center', 'Massive Covered Yards', 'Moisture Meters'],
    dailyArrivalTonnes: 8500,
    crowdLevel: 'High during season',
    primaryCommodities: ['wheat', 'potato', 'cotton']
  },
  {
    id: 'ludhiana-dana-mandi',
    name: 'Ludhiana Main Dana Mandi',
    marathiName: 'लुधियाना मुख्य दाणा मंडी',
    hindiName: 'लुधियाना दाना मंडी',
    state: 'Punjab',
    district: 'Ludhiana',
    lat: 30.8950,
    lng: 75.8620,
    marketFeePercent: 1.1,
    weighingFeePerQuintal: 3.5,
    unloadingFeePerQuintal: 6,
    isEnamLinked: true,
    rating: 4.4,
    facilities: ['Weighbridges', 'Grain Storage', 'Direct Buyer Links'],
    dailyArrivalTonnes: 4100,
    crowdLevel: 'Moderate',
    primaryCommodities: ['wheat', 'potato', 'cotton']
  },

  // Uttar Pradesh Cluster
  {
    id: 'agra-potato-mandi',
    name: 'Agra Khandari Potato & Grain Mandi',
    marathiName: 'आग्रा बटाटा व धान्य मंडी',
    hindiName: 'आगरा खंदारी आलू व अनाज मंडी',
    state: 'Uttar Pradesh',
    district: 'Agra',
    lat: 27.1810,
    lng: 78.0120,
    marketFeePercent: 1.25,
    weighingFeePerQuintal: 4,
    unloadingFeePerQuintal: 8,
    isEnamLinked: true,
    rating: 4.6,
    facilities: ['Cold Storage Corridors', 'Direct Highway Gate', 'Fast Weighment'],
    dailyArrivalTonnes: 4800,
    crowdLevel: 'High',
    primaryCommodities: ['potato', 'wheat', 'mustard', 'garlic']
  },
  {
    id: 'farrukhabad-potato-yard',
    name: 'Farrukhabad Saat Rasta Mandi',
    marathiName: 'फर्रुखाबाद बटाटा मंडी',
    hindiName: 'फर्रुखाबाद सात रास्ता आलू टर्मिनल मंडी',
    state: 'Uttar Pradesh',
    district: 'Farrukhabad',
    lat: 27.3880,
    lng: 79.5890,
    marketFeePercent: 1.1,
    weighingFeePerQuintal: 3,
    unloadingFeePerQuintal: 6,
    isEnamLinked: true,
    rating: 4.8,
    facilities: ['National Potato Dispatch Railhead', 'Grading Belts', 'Farmer Lodge'],
    dailyArrivalTonnes: 6200,
    crowdLevel: 'Very High',
    primaryCommodities: ['potato', 'garlic', 'wheat']
  },

  // Gujarat Cluster
  {
    id: 'rajkot-bedi-yard',
    name: 'Rajkot Bedi Marketing Yard APMC',
    marathiName: 'राजकोट बेडी मार्केट यार्ड',
    hindiName: 'राजकोट बेडी मार्केटिंग यार्ड',
    state: 'Gujarat',
    district: 'Rajkot',
    lat: 22.3110,
    lng: 70.8080,
    marketFeePercent: 1.0,
    weighingFeePerQuintal: 3.5,
    unloadingFeePerQuintal: 6,
    isEnamLinked: true,
    rating: 4.7,
    facilities: ['Automated Auction Counters', 'e-NAM Live Terminals', 'Quality Lab'],
    dailyArrivalTonnes: 5100,
    crowdLevel: 'High',
    primaryCommodities: ['cotton', 'groundnut', 'wheat', 'soybean', 'chilli']
  },
  {
    id: 'gondal-apmc-yard',
    name: 'Gondal APMC Mega Marketing Yard',
    marathiName: 'गोंडल कृषी उत्पन्न बाजार',
    hindiName: 'गोंडल एपीएमसी विशाल मार्केटिंग यार्ड',
    state: 'Gujarat',
    district: 'Gondal',
    lat: 21.9660,
    lng: 70.7990,
    marketFeePercent: 0.95,
    weighingFeePerQuintal: 3,
    unloadingFeePerQuintal: 5.5,
    isEnamLinked: true,
    rating: 4.9,
    facilities: ['Chilli & Groundnut Benchmark Hub', '100% Digital Weighing', 'Direct Bank RTGS'],
    dailyArrivalTonnes: 4400,
    crowdLevel: 'High',
    primaryCommodities: ['chilli', 'groundnut', 'onion', 'garlic', 'cotton']
  },

  // Rajasthan Cluster
  {
    id: 'kota-bhamashah-mandi',
    name: 'Kota Bhamashah Krishi Upaj Mandi',
    marathiName: 'कोटा भामाशाह कृषी मंडी',
    hindiName: 'कोटा भामाशाह कृषि उपज मंडी (विशाल परिसर)',
    state: 'Rajasthan',
    district: 'Kota',
    lat: 25.2180,
    lng: 75.8710,
    marketFeePercent: 1.2,
    weighingFeePerQuintal: 4,
    unloadingFeePerQuintal: 7,
    isEnamLinked: true,
    rating: 4.8,
    facilities: ['State-of-art e-NAM Hub', 'Soybean / Garlic Testing Lab', 'Farmer Rest Rooms'],
    dailyArrivalTonnes: 4600,
    crowdLevel: 'High',
    primaryCommodities: ['garlic', 'soybean', 'wheat', 'mustard', 'coriander']
  },

  // Andhra Pradesh & Telangana Cluster
  {
    id: 'guntur-chilli-mandi',
    name: 'Guntur Asia Largest Red Chilli Yard',
    marathiName: 'गुंटूर मिरची मार्केट',
    hindiName: 'गुंटूर लाल मिर्च एशिया की सबसे बड़ी मंडी',
    state: 'Andhra Pradesh',
    district: 'Guntur',
    lat: 16.3120,
    lng: 80.4410,
    marketFeePercent: 1.1,
    weighingFeePerQuintal: 3,
    unloadingFeePerQuintal: 6,
    isEnamLinked: true,
    rating: 4.9,
    facilities: ['International Cold Storage Zone', 'SHU Quality Assay', 'Direct Exporter Auctions'],
    dailyArrivalTonnes: 5800,
    crowdLevel: 'Very High',
    primaryCommodities: ['chilli', 'cotton', 'tobacco']
  },
  {
    id: 'madanapalle-tomato-market',
    name: 'Madanapalle APMC Tomato Special Terminal',
    marathiName: 'मदनापल्ले टोमॅटो मार्केट',
    hindiName: 'मदनापल्ले एपीएमसी विशेष टमाटर मंडी',
    state: 'Andhra Pradesh',
    district: 'Chittoor (Madanapalle)',
    lat: 13.5530,
    lng: 78.5040,
    marketFeePercent: 1.15,
    weighingFeePerQuintal: 3,
    unloadingFeePerQuintal: 6,
    isEnamLinked: true,
    rating: 4.7,
    facilities: ['Tomato Daily Auction Platform', 'Pre-cooling Facilities'],
    dailyArrivalTonnes: 3600,
    crowdLevel: 'High',
    primaryCommodities: ['tomato', 'mango', 'vegetables']
  },
  {
    id: 'khammam-chilli-market',
    name: 'Khammam APMC Agriculture Market Yard',
    marathiName: 'खम्मम कृषी बाजार समिती',
    hindiName: 'खम्मम एपीएमसी कृषि बाजार यार्ड',
    state: 'Telangana',
    district: 'Khammam',
    lat: 17.2510,
    lng: 80.1560,
    marketFeePercent: 1.0,
    weighingFeePerQuintal: 3.5,
    unloadingFeePerQuintal: 6.5,
    isEnamLinked: true,
    rating: 4.6,
    facilities: ['Teja Chilli Auction Yard', 'Cotton Moisture Testers'],
    dailyArrivalTonnes: 3200,
    crowdLevel: 'Moderate to High',
    primaryCommodities: ['chilli', 'cotton', 'paddy']
  }
];

export const VEHICLE_PRESETS = [
  {
    id: 'auto',
    name: '3-Wheeler / Loading Auto',
    hindiName: 'लोडिंग ऑटो / थ्री-व्हीलर',
    marathiName: 'लोडिंग रिक्षा',
    capacityQuintals: 8,
    ratePerKm: 9,
    baseLoadingFee: 150,
    icon: '🛺',
    bestFor: 'Small quantities (up to 8 quintals / 800 kg)'
  },
  {
    id: 'bolero',
    name: 'Pickup Truck (Bolero / Dost)',
    hindiName: 'पिकअप गाड़ी (बोलेरो/दोस्त)',
    marathiName: 'पिकअप गाडी',
    capacityQuintals: 20,
    ratePerKm: 14,
    baseLoadingFee: 300,
    icon: '🛻',
    bestFor: 'Medium lots (10 - 20 quintals / 1-2 tonnes)'
  },
  {
    id: 'tractor',
    name: 'Tractor Trolley',
    hindiName: 'ट्रैक्टर ट्रॉली',
    marathiName: 'ट्रॅक्टर ट्रॉली',
    capacityQuintals: 45,
    ratePerKm: 18,
    baseLoadingFee: 450,
    icon: '🚜',
    bestFor: 'Village bulk lots (25 - 45 quintals)'
  },
  {
    id: 'minitruck',
    name: 'Mini Truck (Tata 407 / 709)',
    hindiName: 'मिनी ट्रक (407)',
    marathiName: 'मिनी ट्रक',
    capacityQuintals: 55,
    ratePerKm: 22,
    baseLoadingFee: 600,
    icon: '🚚',
    bestFor: 'Bulk lots (40 - 60 quintals / 4-6 tonnes)'
  },
  {
    id: 'largetruck',
    name: 'Heavy 10-Tonner Truck',
    hindiName: 'बड़ा 10-टन ट्रक',
    marathiName: 'मोठा १० टन ट्रक',
    capacityQuintals: 100,
    ratePerKm: 32,
    baseLoadingFee: 900,
    icon: '🚛',
    bestFor: 'FPO / Aggregated lots (80 - 100+ quintals)'
  }
];